"""empty message

Revision ID: 00e4640f12a6
Revises: 9d2d2425d3f1
Create Date: 2019-08-07 16:13:34.831844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00e4640f12a6'
down_revision = '9d2d2425d3f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('supplier', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('supplier', 'image_url')
    # ### end Alembic commands ###
