"""empty message

Revision ID: 04c2243c4acb
Revises: 39b68d58aa2b
Create Date: 2019-07-31 16:10:24.788971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04c2243c4acb'
down_revision = '39b68d58aa2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aps_employee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('employee_no', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('aps_notice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('publish_date', sa.Date(), nullable=True),
    sa.Column('notice_type', sa.String(), nullable=True),
    sa.Column('agency_id', sa.Integer(), nullable=True),
    sa.Column('classification_from', sa.String(), nullable=True),
    sa.Column('classification', sa.String(), nullable=True),
    sa.Column('position_details', sa.String(), nullable=True),
    sa.Column('position', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['agency_id'], ['agency.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('agency', sa.Column('portfolio', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agency', 'portfolio')
    op.drop_table('aps_notice')
    op.drop_table('aps_employee')
    # ### end Alembic commands ###
