"""empty message

Revision ID: 0533be519bd6
Revises: 5d277680490e
Create Date: 2019-07-12 08:09:26.584642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0533be519bd6'
down_revision = '5d277680490e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('op', 'panel_arrangement')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('op', sa.Column('panel_arrangement', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
