"""empty message

Revision ID: 0563efe3a6c3
Revises: db7f01b2b1ac
Create Date: 2019-07-11 17:42:29.105547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0563efe3a6c3'
down_revision = 'db7f01b2b1ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('op', sa.Column('address_for_lodgement', sa.String(), nullable=True))
    op.add_column('op', sa.Column('atm_type', sa.String(), nullable=True))
    op.add_column('op', sa.Column('close_date', sa.String(), nullable=True))
    op.add_column('op', sa.Column('conditions_for_participation', sa.String(), nullable=True))
    op.add_column('op', sa.Column('description', sa.String(), nullable=True))
    op.add_column('op', sa.Column('multi_agency_access', sa.String(), nullable=True))
    op.add_column('op', sa.Column('multi_stage', sa.String(), nullable=True))
    op.add_column('op', sa.Column('panel_arrangement', sa.String(), nullable=True))
    op.add_column('op', sa.Column('publish_date', sa.String(), nullable=True))
    op.add_column('op', sa.Column('timeframe_for_delivery', sa.String(), nullable=True))
    op.drop_index('ix_op_atm_id', table_name='op')
    op.drop_index('ix_op_title', table_name='op')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_op_title', 'op', ['title'], unique=False)
    op.create_index('ix_op_atm_id', 'op', ['atm_id'], unique=False)
    op.drop_column('op', 'timeframe_for_delivery')
    op.drop_column('op', 'publish_date')
    op.drop_column('op', 'panel_arrangement')
    op.drop_column('op', 'multi_stage')
    op.drop_column('op', 'multi_agency_access')
    op.drop_column('op', 'description')
    op.drop_column('op', 'conditions_for_participation')
    op.drop_column('op', 'close_date')
    op.drop_column('op', 'atm_type')
    op.drop_column('op', 'address_for_lodgement')
    # ### end Alembic commands ###
