"""empty message

Revision ID: 05ca8a349d13
Revises: 5b22840de329
Create Date: 2019-07-31 16:37:25.752749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05ca8a349d13'
down_revision = '5b22840de329'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notice', sa.Column('agency_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'notice', 'agency', ['agency_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notice', type_='foreignkey')
    op.drop_column('notice', 'agency_id')
    # ### end Alembic commands ###
