"""empty message

Revision ID: 15c9c393aa09
Revises: e215fbe1bbb3
Create Date: 2019-08-19 12:19:58.598612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15c9c393aa09'
down_revision = 'e215fbe1bbb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('supplier_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'supplier', ['supplier_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'supplier_id')
    # ### end Alembic commands ###
