"""empty message

Revision ID: 174aed865856
Revises: b5cc60c4b02f
Create Date: 2019-07-10 15:42:07.751932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '174aed865856'
down_revision = 'b5cc60c4b02f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment')
    # ### end Alembic commands ###
