"""empty message

Revision ID: 1765c500b344
Revises: 7d59cc671b72
Create Date: 2019-07-12 13:09:03.497932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1765c500b344'
down_revision = '7d59cc671b72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('unspsc', sa.Column('level_int', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('unspsc', 'level_int')
    # ### end Alembic commands ###
