"""empty message

Revision ID: 17a8d4ca25a4
Revises: 99d56d2e2661
Create Date: 2019-07-14 21:08:37.697441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17a8d4ca25a4'
down_revision = '99d56d2e2661'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contract', 'publish_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contract', sa.Column('publish_date', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
