"""empty message

Revision ID: 1e87607e8433
Revises: e67c4ab3a703
Create Date: 2019-07-31 20:17:35.713007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e87607e8433'
down_revision = 'e67c4ab3a703'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notice', sa.Column('state', sa.String(), nullable=True))
    op.add_column('notice', sa.Column('suburb', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notice', 'suburb')
    op.drop_column('notice', 'state')
    # ### end Alembic commands ###
