"""empty message

Revision ID: 22b3b80b95b7
Revises: 44efd55d14e7
Create Date: 2019-07-10 08:44:47.118932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22b3b80b95b7'
down_revision = '44efd55d14e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('opportunities', sa.Column('unspscid_segment_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'opportunities', 'unspsc', ['unspscid_segment_id'], ['id'])
    op.drop_column('opportunities', 'unspscid_commodity')
    op.drop_column('opportunities', 'unspscid_class')
    op.drop_column('opportunities', 'unspscid_family')
    op.drop_column('opportunities', 'unspscid_segment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('opportunities', sa.Column('unspscid_segment', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('opportunities', sa.Column('unspscid_family', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('opportunities', sa.Column('unspscid_class', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('opportunities', sa.Column('unspscid_commodity', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'opportunities', type_='foreignkey')
    op.drop_column('opportunities', 'unspscid_segment_id')
    # ### end Alembic commands ###
