"""empty message

Revision ID: 22e48bc39182
Revises: c25a16d8cd05
Create Date: 2019-07-25 13:22:00.271194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22e48bc39182'
down_revision = 'c25a16d8cd05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contract', sa.Column('unspsc_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'contract', 'unspsc', ['unspsc_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contract', type_='foreignkey')
    op.drop_column('contract', 'unspsc_id')
    # ### end Alembic commands ###
