"""empty message

Revision ID: 28ee196b054d
Revises: db862c8c15a9
Create Date: 2019-07-11 18:30:53.888036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28ee196b054d'
down_revision = 'db862c8c15a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_agency_name'), 'agency', ['name'], unique=False)
    op.drop_index('ix_user_first_name', table_name='user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_user_first_name', 'user', ['first_name'], unique=False)
    op.drop_index(op.f('ix_agency_name'), table_name='agency')
    # ### end Alembic commands ###
