"""empty message

Revision ID: 2bcb57d99714
Revises: 2072f25fb246
Create Date: 2019-07-10 15:35:00.392821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bcb57d99714'
down_revision = '2072f25fb246'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('author')
    op.drop_table('users')
    op.drop_table('book')
    op.drop_table('orders')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('opportunity_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('unspsc_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['opportunity_id'], [u'opportunities.id'], name=u'orders_opportunity_id_fkey'),
    sa.ForeignKeyConstraint(['unspsc_id'], [u'unspsc.id'], name=u'orders_unspsc_id_fkey'),
    sa.PrimaryKeyConstraint('id', name=u'orders_pkey')
    )
    op.create_table('book',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['author_id'], [u'author.id'], name=u'book_author_id_fkey'),
    sa.PrimaryKeyConstraint('id', name=u'book_pkey')
    )
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'users_pkey')
    )
    op.create_table('author',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'author_pkey')
    )
    # ### end Alembic commands ###
