"""empty message

Revision ID: 31e56748e181
Revises: 3c1b90c6c0c7
Create Date: 2019-07-09 23:30:29.298785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31e56748e181'
down_revision = '3c1b90c6c0c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('opportunities', sa.Column('unspscid_commodity', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'opportunities', 'unspsc', ['unspscid_commodity'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'opportunities', type_='foreignkey')
    op.drop_column('opportunities', 'unspscid_commodity')
    # ### end Alembic commands ###
