"""empty message

Revision ID: 31f58f3396f8
Revises: 6395d38cc581
Create Date: 2019-08-15 08:39:50.603455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31f58f3396f8'
down_revision = '6395d38cc581'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('supplier_matrix', sa.Column('data', sa.JSON(), nullable=True))
    op.drop_column('supplier_matrix', 'matrix')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('supplier_matrix', sa.Column('matrix', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('supplier_matrix', 'data')
    # ### end Alembic commands ###
