"""empty message

Revision ID: 33f301d0b58a
Revises: 174aed865856
Create Date: 2019-07-10 16:14:30.769049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33f301d0b58a'
down_revision = '174aed865856'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'comment_user_id_fkey', 'comment', type_='foreignkey')
    op.drop_column('comment', 'user_id')
    op.add_column('user', sa.Column('comment_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'comment', ['comment_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'comment_id')
    op.add_column('comment', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(u'comment_user_id_fkey', 'comment', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
