"""empty message

Revision ID: 387f0a110926
Revises: a8c388ad1f0d
Create Date: 2019-07-08 16:30:10.292200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '387f0a110926'
down_revision = 'a8c388ad1f0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('opportunities', sa.Column('opportunity_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('opportunities', 'opportunity_id')
    # ### end Alembic commands ###
