"""empty message

Revision ID: 39b68d58aa2b
Revises: 53ead1f30c8d
Create Date: 2019-07-30 21:58:55.202562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39b68d58aa2b'
down_revision = '53ead1f30c8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('son',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('austender_id', sa.String(), nullable=True),
    sa.Column('austender_link', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('contract', sa.Column('son_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'contract', 'son', ['son_id'], ['id'])
    op.drop_column('contract', 'son_austender_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contract', sa.Column('son_austender_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'contract', type_='foreignkey')
    op.drop_column('contract', 'son_id')
    op.drop_table('son')
    # ### end Alembic commands ###
