"""empty message

Revision ID: 3c1b90c6c0c7
Revises: 87bd49d92089
Create Date: 2019-07-09 07:08:18.836464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c1b90c6c0c7'
down_revision = '87bd49d92089'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unspsc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unspsc', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('level', sa.String(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('unspsc')
    # ### end Alembic commands ###
