"""empty message

Revision ID: 3db2e6217bfe
Revises: 8d04d2ebae33
Create Date: 2019-07-25 07:59:30.431512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3db2e6217bfe'
down_revision = '8d04d2ebae33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contract', sa.Column('category_temp_title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contract', 'category_temp_title')
    # ### end Alembic commands ###
