"""empty message

Revision ID: 44efd55d14e7
Revises: b2610067ac92
Create Date: 2019-07-10 00:06:00.729578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44efd55d14e7'
down_revision = 'b2610067ac92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('opportunities', sa.Column('unspscid_class', sa.Integer(), nullable=True))
    op.add_column('opportunities', sa.Column('unspscid_commodity', sa.Integer(), nullable=True))
    op.add_column('opportunities', sa.Column('unspscid_family', sa.Integer(), nullable=True))
    op.drop_constraint(u'opportunities_unspscid_segment_fkey', 'opportunities', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(u'opportunities_unspscid_segment_fkey', 'opportunities', 'unspsc', ['unspscid_segment'], ['id'])
    op.drop_column('opportunities', 'unspscid_family')
    op.drop_column('opportunities', 'unspscid_commodity')
    op.drop_column('opportunities', 'unspscid_class')
    # ### end Alembic commands ###
