"""empty message

Revision ID: 4542680f053e
Revises: fc99c9995bcf
Create Date: 2019-08-01 14:56:11.340380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4542680f053e'
down_revision = 'fc99c9995bcf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contract', sa.Column('branch_id', sa.Integer(), nullable=True))
    op.add_column('contract', sa.Column('contact_name', sa.String(), nullable=True))
    op.add_column('contract', sa.Column('division_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'contract', 'division', ['division_id'], ['id'])
    op.create_foreign_key(None, 'contract', 'branch', ['branch_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contract', type_='foreignkey')
    op.drop_constraint(None, 'contract', type_='foreignkey')
    op.drop_column('contract', 'division_id')
    op.drop_column('contract', 'contact_name')
    op.drop_column('contract', 'branch_id')
    # ### end Alembic commands ###
