"""empty message

Revision ID: 503c9982477c
Revises: 1cff2176fa82
Create Date: 2019-07-12 08:03:48.700362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '503c9982477c'
down_revision = '1cff2176fa82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('op', 'panel_arrangement')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('op', sa.Column('panel_arrangement', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
