"""empty message

Revision ID: 524bce2938b5
Revises: 31f58f3396f8
Create Date: 2019-08-15 08:41:14.763173

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '524bce2938b5'
down_revision = '31f58f3396f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('supplier_matrix', sa.Column('json', sa.JSON(), nullable=True))
    op.drop_column('supplier_matrix', 'data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('supplier_matrix', sa.Column('data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('supplier_matrix', 'json')
    # ### end Alembic commands ###
