"""empty message

Revision ID: 53ead1f30c8d
Revises: 95849fe47fec
Create Date: 2019-07-30 21:32:53.514987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53ead1f30c8d'
down_revision = '95849fe47fec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contract', 'panel_austender_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contract', sa.Column('panel_austender_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
