"""empty message

Revision ID: 571cd69ff47b
Revises: 28ee196b054d
Create Date: 2019-07-11 18:34:05.937922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '571cd69ff47b'
down_revision = '28ee196b054d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_agency_name', table_name='agency')
    op.drop_index('ix_user_email', table_name='user')
    op.drop_index('ix_user_last_name', table_name='user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_user_last_name', 'user', ['last_name'], unique=False)
    op.create_index('ix_user_email', 'user', ['email'], unique=False)
    op.create_index('ix_agency_name', 'agency', ['name'], unique=False)
    # ### end Alembic commands ###
