"""empty message

Revision ID: 57d9f4466d74
Revises: 17a8d4ca25a4
Create Date: 2019-07-14 21:13:34.415756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57d9f4466d74'
down_revision = '17a8d4ca25a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contract', sa.Column('publish_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contract', 'publish_date')
    # ### end Alembic commands ###
