"""empty message

Revision ID: 5d15d85b9b0c
Revises: 57d9f4466d74
Create Date: 2019-07-15 13:40:54.089137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d15d85b9b0c'
down_revision = '57d9f4466d74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contract', sa.Column('contract_duration', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contract', 'contract_duration')
    # ### end Alembic commands ###
