"""empty message

Revision ID: 5d277680490e
Revises: 503c9982477c
Create Date: 2019-07-12 08:03:59.868491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d277680490e'
down_revision = '503c9982477c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('op', sa.Column('panel_arrangement', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('op', 'panel_arrangement')
    # ### end Alembic commands ###
