"""empty message

Revision ID: 5d6c759ed74c
Revises: 571cd69ff47b
Create Date: 2019-07-11 18:41:23.058830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d6c759ed74c'
down_revision = '571cd69ff47b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agency', sa.Column('title', sa.String(), nullable=True))
    op.drop_column('agency', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agency', sa.Column('name', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.drop_column('agency', 'title')
    # ### end Alembic commands ###
