"""empty message

Revision ID: 616ebf139261
Revises: 04c2243c4acb
Create Date: 2019-07-31 16:25:42.143673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '616ebf139261'
down_revision = '04c2243c4acb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('aps_notice')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aps_notice',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('publish_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('notice_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('agency_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('classification_from', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('classification', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('position_details', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('position', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['agency_id'], ['agency.id'], name='aps_notice_agency_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='aps_notice_pkey')
    )
    # ### end Alembic commands ###
