"""empty message

Revision ID: 6395d38cc581
Revises: 9ebd80bf35ef
Create Date: 2019-08-15 08:19:13.594377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6395d38cc581'
down_revision = '9ebd80bf35ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('supplier_matrix', sa.Column('financial_quarter', sa.Integer(), nullable=True))
    op.add_column('supplier_matrix', sa.Column('matrix_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('supplier_matrix', 'matrix_type')
    op.drop_column('supplier_matrix', 'financial_quarter')
    # ### end Alembic commands ###
