"""empty message

Revision ID: 7345e6dfb804
Revises: e6744c221148
Create Date: 2019-07-12 08:10:50.181729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7345e6dfb804'
down_revision = 'e6744c221148'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('op', sa.Column('multi_agency_access', sa.Integer(), nullable=True))
    op.add_column('op', sa.Column('multi_stage', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('op', 'multi_stage')
    op.drop_column('op', 'multi_agency_access')
    # ### end Alembic commands ###
