"""empty message

Revision ID: 7975eef7c232
Revises: c272b6f19c5c
Create Date: 2019-07-10 13:19:43.290084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7975eef7c232'
down_revision = 'c272b6f19c5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('unspscs', sa.Column('id', sa.Integer(), nullable=False))
    op.alter_column('unspscs', 'opportunity_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('unspscs', 'unspsc_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('unspscs', 'unspsc_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('unspscs', 'opportunity_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('unspscs', 'id')
    # ### end Alembic commands ###
