"""empty message

Revision ID: 7d59cc671b72
Revises: 7345e6dfb804
Create Date: 2019-07-12 08:28:58.044094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d59cc671b72'
down_revision = '7345e6dfb804'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('unspsc', sa.Column('scraped', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('unspsc', 'scraped')
    # ### end Alembic commands ###
