"""empty message

Revision ID: 7f0f39e7be4c
Revises: 05ca8a349d13
Create Date: 2019-07-31 16:37:57.224752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f0f39e7be4c'
down_revision = '05ca8a349d13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notice', sa.Column('classification', sa.String(), nullable=True))
    op.add_column('notice', sa.Column('classification_from', sa.String(), nullable=True))
    op.add_column('notice', sa.Column('notice_type', sa.String(), nullable=True))
    op.add_column('notice', sa.Column('position', sa.String(), nullable=True))
    op.add_column('notice', sa.Column('position_details', sa.String(), nullable=True))
    op.add_column('notice', sa.Column('publish_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notice', 'publish_date')
    op.drop_column('notice', 'position_details')
    op.drop_column('notice', 'position')
    op.drop_column('notice', 'notice_type')
    op.drop_column('notice', 'classification_from')
    op.drop_column('notice', 'classification')
    # ### end Alembic commands ###
