"""empty message

Revision ID: 829abf95bd95
Revises: 048f3d132e5d
Create Date: 2019-07-08 10:57:42.939580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '829abf95bd95'
down_revision = '048f3d132e5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
