"""empty message

Revision ID: 840f007a89d1
Revises: 0563efe3a6c3
Create Date: 2019-07-11 18:21:42.175579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '840f007a89d1'
down_revision = '0563efe3a6c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agency',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agency_name'), 'agency', ['name'], unique=False)
    op.add_column(u'op', sa.Column('agency_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'op', 'agency', ['agency_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'op', type_='foreignkey')
    op.drop_column(u'op', 'agency_id')
    op.drop_index(op.f('ix_agency_name'), table_name='agency')
    op.drop_table('agency')
    # ### end Alembic commands ###
