"""empty message

Revision ID: 8426cf645c38
Revises: 372774ba2961
Create Date: 2019-08-13 10:07:28.786803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8426cf645c38'
down_revision = '372774ba2961'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('supplier_address_id_fkey', 'supplier', type_='foreignkey')
    op.drop_column('supplier', 'address_id')
    op.add_column('supplier_address', sa.Column('supplier_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'supplier_address', 'supplier', ['supplier_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'supplier_address', type_='foreignkey')
    op.drop_column('supplier_address', 'supplier_id')
    op.add_column('supplier', sa.Column('address_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('supplier_address_id_fkey', 'supplier', 'supplier_address', ['address_id'], ['id'])
    # ### end Alembic commands ###
