"""empty message

Revision ID: 8816f1badf38
Revises: 0533be519bd6
Create Date: 2019-07-12 08:09:38.410680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8816f1badf38'
down_revision = '0533be519bd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('op', sa.Column('panel_arrangement', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('op', 'panel_arrangement')
    # ### end Alembic commands ###
