"""empty message

Revision ID: 8d04d2ebae33
Revises: 
Create Date: 2019-07-15 15:08:11.414419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d04d2ebae33'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addenda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('published', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agency',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contract',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('cn_id', sa.String(), nullable=True),
    sa.Column('contract_start', sa.Date(), nullable=True),
    sa.Column('contract_end', sa.Date(), nullable=True),
    sa.Column('contract_duration', sa.Integer(), nullable=True),
    sa.Column('confidentiality_contract', sa.String(), nullable=True),
    sa.Column('agency_reference_id', sa.String(), nullable=True),
    sa.Column('confidentiality_outputs', sa.String(), nullable=True),
    sa.Column('contract_value', sa.String(), nullable=True),
    sa.Column('procurement_method', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('publish_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('page',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('unspsc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unspsc', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('level', sa.String(), nullable=True),
    sa.Column('level_int', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('scraped', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('op',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('atm_id', sa.String(), nullable=True),
    sa.Column('conditions_for_participation', sa.String(), nullable=True),
    sa.Column('panel_arrangement', sa.Integer(), nullable=True),
    sa.Column('timeframe_for_delivery', sa.String(), nullable=True),
    sa.Column('close_date', sa.Date(), nullable=True),
    sa.Column('multi_stage', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('address_for_lodgement', sa.String(), nullable=True),
    sa.Column('publish_date', sa.Date(), nullable=True),
    sa.Column('atm_type', sa.String(), nullable=True),
    sa.Column('multi_agency_access', sa.Integer(), nullable=True),
    sa.Column('agency_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['agency_id'], ['agency.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tags',
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['page.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('tag_id', 'page_id')
    )
    op.create_table('unspsc_op',
    sa.Column('unspsc_id', sa.Integer(), nullable=False),
    sa.Column('op_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['op_id'], ['op.id'], ),
    sa.ForeignKeyConstraint(['unspsc_id'], ['unspsc.id'], ),
    sa.PrimaryKeyConstraint('unspsc_id', 'op_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('unspsc_op')
    op.drop_table('tags')
    op.drop_table('op')
    op.drop_table('comment')
    op.drop_table('user')
    op.drop_table('unspsc')
    op.drop_table('tag')
    op.drop_table('page')
    op.drop_table('location')
    op.drop_table('contract')
    op.drop_table('agency')
    op.drop_table('addenda')
    # ### end Alembic commands ###
