"""empty message

Revision ID: 968cbee87d9b
Revises: 1765c500b344
Create Date: 2019-07-13 08:54:06.483334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '968cbee87d9b'
down_revision = '1765c500b344'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contract',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contract')
    # ### end Alembic commands ###
