"""empty message

Revision ID: 975e4c9c80ce
Revises: 309b52aa8a36
Create Date: 2019-08-13 09:58:14.476630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '975e4c9c80ce'
down_revision = '309b52aa8a36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supplier_address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('postal_address', sa.String(), nullable=True),
    sa.Column('town_city', sa.String(), nullable=True),
    sa.Column('postcode', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('supplier_address')
    # ### end Alembic commands ###
