"""empty message

Revision ID: 9822fe75b239
Revises: 1e87607e8433
Create Date: 2019-07-31 21:03:31.877241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9822fe75b239'
down_revision = '1e87607e8433'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('gender', sa.String(), nullable=True))
    op.add_column('notice', sa.Column('advertised', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notice', 'advertised')
    op.drop_column('employee', 'gender')
    # ### end Alembic commands ###
