"""empty message

Revision ID: 988b206ab2ee
Revises: d6b8ef5df9c3
Create Date: 2019-07-10 23:09:41.885518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '988b206ab2ee'
down_revision = 'd6b8ef5df9c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('opportunities')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('opportunities',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('atm_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'opportunities_pkey')
    )
    # ### end Alembic commands ###
