"""empty message

Revision ID: 989289d10d40
Revises: 15c9c393aa09
Create Date: 2019-08-21 10:34:35.642820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '989289d10d40'
down_revision = '15c9c393aa09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('competitor', sa.Column('agency_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'competitor', 'agency', ['agency_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'competitor', type_='foreignkey')
    op.drop_column('competitor', 'agency_id')
    # ### end Alembic commands ###
