"""empty message

Revision ID: 99d56d2e2661
Revises: bfc3380d0907
Create Date: 2019-07-14 21:06:49.217240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99d56d2e2661'
down_revision = 'bfc3380d0907'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contract', sa.Column('contract_end', sa.Date(), nullable=True))
    op.add_column('contract', sa.Column('contract_start', sa.Date(), nullable=True))
    op.drop_column('contract', 'contract_period')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contract', sa.Column('contract_period', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('contract', 'contract_start')
    op.drop_column('contract', 'contract_end')
    # ### end Alembic commands ###
