"""empty message

Revision ID: 9a4653634c61
Revises: ae3b544ed6db
Create Date: 2019-07-11 20:57:56.627745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a4653634c61'
down_revision = 'ae3b544ed6db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('op', sa.Column('close_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('op', 'close_date')
    # ### end Alembic commands ###
