"""empty message

Revision ID: 9ebd80bf35ef
Revises: f866c235bd1e
Create Date: 2019-08-14 14:59:14.157442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ebd80bf35ef'
down_revision = 'f866c235bd1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supplier_matrix',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matrix', sa.String(), nullable=True),
    sa.Column('financial_year', sa.Integer(), nullable=True),
    sa.Column('created', sa.Date(), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('supplier_matrix')
    # ### end Alembic commands ###
