"""empty message

Revision ID: a4fe457041e0
Revises: 00e4640f12a6
Create Date: 2019-08-07 18:28:43.319549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4fe457041e0'
down_revision = '00e4640f12a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agency', sa.Column('image_url', sa.String(), nullable=True))
    op.add_column('employee', sa.Column('linkedin', sa.String(), nullable=True))
    op.add_column('user', sa.Column('admin', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'admin')
    op.drop_column('employee', 'linkedin')
    op.drop_column('agency', 'image_url')
    # ### end Alembic commands ###
