"""empty message

Revision ID: a526dfa0357b
Revises: da6a64b1752c
Create Date: 2019-07-10 16:17:49.885261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a526dfa0357b'
down_revision = 'da6a64b1752c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('comment_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'comment', ['comment_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'comment_id')
    # ### end Alembic commands ###
