"""empty message

Revision ID: a6b3d16461d0
Revises: 4542680f053e
Create Date: 2019-08-06 10:54:41.861499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6b3d16461d0'
down_revision = '4542680f053e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contract', sa.Column('original_contract_value', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contract', 'original_contract_value')
    # ### end Alembic commands ###
