"""empty message

Revision ID: b2610067ac92
Revises: c50610476ddd
Create Date: 2019-07-09 23:45:18.460165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2610067ac92'
down_revision = 'c50610476ddd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('opportunities', sa.Column('unspscid_segment', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'opportunities', 'unspsc', ['unspscid_segment'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'opportunities', type_='foreignkey')
    op.drop_column('opportunities', 'unspscid_segment')
    # ### end Alembic commands ###
