"""empty message

Revision ID: b89fa40c6fef
Revises: bf5a44c50e15
Create Date: 2019-09-19 10:35:00.950957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b89fa40c6fef'
down_revision = 'bf5a44c50e15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('competitor', sa.Column('competitor_earnings', sa.Float(), nullable=True))
    op.add_column('competitor', sa.Column('supplier_earnings', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('competitor', 'supplier_earnings')
    op.drop_column('competitor', 'competitor_earnings')
    # ### end Alembic commands ###
