"""empty message

Revision ID: bb2703846bc3
Revises: db2a54c36528
Create Date: 2019-07-10 13:41:17.600122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb2703846bc3'
down_revision = 'db2a54c36528'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('opportunity_id', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('unspsc_id', sa.Integer(), nullable=True))
    op.drop_constraint(u'orders_un_id_fkey', 'orders', type_='foreignkey')
    op.drop_constraint(u'orders_opp_id_fkey', 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'unspsc', ['unspsc_id'], ['id'])
    op.create_foreign_key(None, 'orders', 'opportunities', ['opportunity_id'], ['id'])
    op.drop_column('orders', 'un_id')
    op.drop_column('orders', 'opp_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('opp_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('un_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key(u'orders_opp_id_fkey', 'orders', 'opportunities', ['opp_id'], ['id'])
    op.create_foreign_key(u'orders_un_id_fkey', 'orders', 'unspsc', ['un_id'], ['id'])
    op.drop_column('orders', 'unspsc_id')
    op.drop_column('orders', 'opportunity_id')
    # ### end Alembic commands ###
