"""empty message

Revision ID: bf5a44c50e15
Revises: 989289d10d40
Create Date: 2019-08-30 16:19:17.591976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf5a44c50e15'
down_revision = '989289d10d40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('competitor', sa.Column('branch_id', sa.Integer(), nullable=True))
    op.add_column('competitor', sa.Column('category', sa.String(), nullable=True))
    op.add_column('competitor', sa.Column('division_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'competitor', 'branch', ['branch_id'], ['id'])
    op.create_foreign_key(None, 'competitor', 'division', ['division_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'competitor', type_='foreignkey')
    op.drop_constraint(None, 'competitor', type_='foreignkey')
    op.drop_column('competitor', 'division_id')
    op.drop_column('competitor', 'category')
    op.drop_column('competitor', 'branch_id')
    # ### end Alembic commands ###
