"""empty message

Revision ID: bfc3380d0907
Revises: 968cbee87d9b
Create Date: 2019-07-13 10:25:02.125589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfc3380d0907'
down_revision = '968cbee87d9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contract', sa.Column('agency_reference_id', sa.String(), nullable=True))
    op.add_column('contract', sa.Column('cn_id', sa.String(), nullable=True))
    op.add_column('contract', sa.Column('confidentiality_contract', sa.String(), nullable=True))
    op.add_column('contract', sa.Column('confidentiality_outputs', sa.String(), nullable=True))
    op.add_column('contract', sa.Column('contract_period', sa.String(), nullable=True))
    op.add_column('contract', sa.Column('contract_value', sa.String(), nullable=True))
    op.add_column('contract', sa.Column('description', sa.String(), nullable=True))
    op.add_column('contract', sa.Column('procurement_method', sa.String(), nullable=True))
    op.add_column('contract', sa.Column('publish_date', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contract', 'publish_date')
    op.drop_column('contract', 'procurement_method')
    op.drop_column('contract', 'description')
    op.drop_column('contract', 'contract_value')
    op.drop_column('contract', 'contract_period')
    op.drop_column('contract', 'confidentiality_outputs')
    op.drop_column('contract', 'confidentiality_contract')
    op.drop_column('contract', 'cn_id')
    op.drop_column('contract', 'agency_reference_id')
    # ### end Alembic commands ###
