"""empty message

Revision ID: c136758b575e
Revises: e3bcd4cf943a
Create Date: 2019-07-10 21:43:28.693724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c136758b575e'
down_revision = 'e3bcd4cf943a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('op',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('atm_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_op_atm_id'), 'op', ['atm_id'], unique=False)
    op.create_index(op.f('ix_op_title'), 'op', ['title'], unique=False)
    op.create_table('opportunities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('atm_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('unspsc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unspsc', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('level', sa.String(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_unspsc_level'), 'unspsc', ['level'], unique=False)
    op.create_index(op.f('ix_unspsc_parent_id'), 'unspsc', ['parent_id'], unique=False)
    op.create_index(op.f('ix_unspsc_title'), 'unspsc', ['title'], unique=False)
    op.create_index(op.f('ix_unspsc_unspsc'), 'unspsc', ['unspsc'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=False)
    op.create_index(op.f('ix_user_first_name'), 'user', ['first_name'], unique=False)
    op.create_index(op.f('ix_user_last_name'), 'user', ['last_name'], unique=False)
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment')
    op.drop_index(op.f('ix_user_last_name'), table_name='user')
    op.drop_index(op.f('ix_user_first_name'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_unspsc_unspsc'), table_name='unspsc')
    op.drop_index(op.f('ix_unspsc_title'), table_name='unspsc')
    op.drop_index(op.f('ix_unspsc_parent_id'), table_name='unspsc')
    op.drop_index(op.f('ix_unspsc_level'), table_name='unspsc')
    op.drop_table('unspsc')
    op.drop_table('opportunities')
    op.drop_index(op.f('ix_op_title'), table_name='op')
    op.drop_index(op.f('ix_op_atm_id'), table_name='op')
    op.drop_table('op')
    # ### end Alembic commands ###
