"""empty message

Revision ID: c25a16d8cd05
Revises: 3db2e6217bfe
Create Date: 2019-07-25 08:44:25.042682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c25a16d8cd05'
down_revision = '3db2e6217bfe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supplier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('abn', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('contract', sa.Column('agency_id', sa.Integer(), nullable=True))
    op.add_column('contract', sa.Column('supplier_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'contract', 'agency', ['agency_id'], ['id'])
    op.create_foreign_key(None, 'contract', 'supplier', ['supplier_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contract', type_='foreignkey')
    op.drop_constraint(None, 'contract', type_='foreignkey')
    op.drop_column('contract', 'supplier_id')
    op.drop_column('contract', 'agency_id')
    op.drop_table('supplier')
    # ### end Alembic commands ###
