"""empty message

Revision ID: c272b6f19c5c
Revises: 22b3b80b95b7
Create Date: 2019-07-10 12:25:11.998029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c272b6f19c5c'
down_revision = '22b3b80b95b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unspscs',
    sa.Column('unspsc_id', sa.Integer(), nullable=False),
    sa.Column('opportunity_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ),
    sa.ForeignKeyConstraint(['unspsc_id'], ['unspsc.id'], ),
    sa.PrimaryKeyConstraint('unspsc_id', 'opportunity_id')
    )
    op.drop_constraint(u'opportunities_unspscid_segment_id_fkey', 'opportunities', type_='foreignkey')
    op.drop_column(u'opportunities', 'unspscid_segment_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'opportunities', sa.Column('unspscid_segment_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(u'opportunities_unspscid_segment_id_fkey', 'opportunities', 'unspsc', ['unspscid_segment_id'], ['id'])
    op.drop_table('unspscs')
    # ### end Alembic commands ###
