"""empty message

Revision ID: c34b7e5648e3
Revises: bb2703846bc3
Create Date: 2019-07-10 13:52:07.051819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c34b7e5648e3'
down_revision = 'bb2703846bc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classes',
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('class_name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('class_id'),
    sa.UniqueConstraint('class_name')
    )
    op.create_table('students',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_fistName', sa.String(length=64), nullable=True),
    sa.Column('user_lastName', sa.String(length=64), nullable=True),
    sa.Column('user_email', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_email')
    )
    op.create_table('student_identifier',
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.class_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['students.user_id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_identifier')
    op.drop_table('students')
    op.drop_table('classes')
    # ### end Alembic commands ###
