"""empty message

Revision ID: c50610476ddd
Revises: 31e56748e181
Create Date: 2019-07-09 23:36:44.328273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c50610476ddd'
down_revision = '31e56748e181'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'opportunities_unspscid_commodity_fkey', 'opportunities', type_='foreignkey')
    op.drop_column('opportunities', 'unspscid_commodity')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('opportunities', sa.Column('unspscid_commodity', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(u'opportunities_unspscid_commodity_fkey', 'opportunities', 'unspsc', ['unspscid_commodity'], ['id'])
    # ### end Alembic commands ###
