"""empty message

Revision ID: cb4a2f3d510c
Revises: 988b206ab2ee
Create Date: 2019-07-10 23:50:52.117501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb4a2f3d510c'
down_revision = '988b206ab2ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('op', sa.Column('unspsc_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'op', 'unspsc', ['unspsc_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'op', type_='foreignkey')
    op.drop_column('op', 'unspsc_id')
    # ### end Alembic commands ###
