"""empty message

Revision ID: d6b8ef5df9c3
Revises: c136758b575e
Create Date: 2019-07-10 22:47:14.724805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6b8ef5df9c3'
down_revision = 'c136758b575e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_unspsc_level', table_name='unspsc')
    op.drop_index('ix_unspsc_parent_id', table_name='unspsc')
    op.drop_index('ix_unspsc_title', table_name='unspsc')
    op.drop_index('ix_unspsc_unspsc', table_name='unspsc')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_unspsc_unspsc', 'unspsc', ['unspsc'], unique=False)
    op.create_index('ix_unspsc_title', 'unspsc', ['title'], unique=False)
    op.create_index('ix_unspsc_parent_id', 'unspsc', ['parent_id'], unique=False)
    op.create_index('ix_unspsc_level', 'unspsc', ['level'], unique=False)
    # ### end Alembic commands ###
