"""empty message

Revision ID: da6a64b1752c
Revises: 33f301d0b58a
Create Date: 2019-07-10 16:17:17.025605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da6a64b1752c'
down_revision = '33f301d0b58a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'user_comment_id_fkey', 'user', type_='foreignkey')
    op.drop_column('user', 'comment_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('comment_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(u'user_comment_id_fkey', 'user', 'comment', ['comment_id'], ['id'])
    # ### end Alembic commands ###
