"""empty message

Revision ID: db7f01b2b1ac
Revises: 4758e305d10e
Create Date: 2019-07-11 13:51:08.976979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db7f01b2b1ac'
down_revision = '4758e305d10e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unspsc_op',
    sa.Column('unspsc_id', sa.Integer(), nullable=False),
    sa.Column('op_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['op_id'], ['op.id'], ),
    sa.ForeignKeyConstraint(['unspsc_id'], ['unspsc.id'], ),
    sa.PrimaryKeyConstraint('unspsc_id', 'op_id')
    )
    op.drop_constraint(u'op_unspsc_id_fkey', 'op', type_='foreignkey')
    op.drop_column(u'op', 'unspsc_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'op', sa.Column('unspsc_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(u'op_unspsc_id_fkey', 'op', 'unspsc', ['unspsc_id'], ['id'])
    op.drop_table('unspsc_op')
    # ### end Alembic commands ###
