"""empty message

Revision ID: db862c8c15a9
Revises: 840f007a89d1
Create Date: 2019-07-11 18:27:17.087868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db862c8c15a9'
down_revision = '840f007a89d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_agency_name', table_name='agency')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_agency_name', 'agency', ['name'], unique=False)
    # ### end Alembic commands ###
