"""empty message

Revision ID: e136a9b5fc25
Revises: a526dfa0357b
Create Date: 2019-07-10 16:26:33.656001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e136a9b5fc25'
down_revision = 'a526dfa0357b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comment', 'user', ['user_id'], ['id'])
    op.drop_constraint(u'user_comment_id_fkey', 'user', type_='foreignkey')
    op.drop_column('user', 'comment_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('comment_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(u'user_comment_id_fkey', 'user', 'comment', ['comment_id'], ['id'])
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_column('comment', 'user_id')
    # ### end Alembic commands ###
