"""empty message

Revision ID: e215fbe1bbb3
Revises: dc094c620604
Create Date: 2019-08-19 09:53:11.430115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e215fbe1bbb3'
down_revision = 'dc094c620604'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('supplier', sa.Column('umbrella', sa.Integer(), nullable=True))
    op.add_column('supplier', sa.Column('umbrella_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('supplier', 'umbrella_id')
    op.drop_column('supplier', 'umbrella')
    # ### end Alembic commands ###
