"""empty message

Revision ID: e3bcd4cf943a
Revises: 520ac8e9abaa
Create Date: 2019-07-10 17:51:21.997656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3bcd4cf943a'
down_revision = '520ac8e9abaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('op',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('atm_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_op_atm_id'), 'op', ['atm_id'], unique=False)
    op.create_index(op.f('ix_op_title'), 'op', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_op_title'), table_name='op')
    op.drop_index(op.f('ix_op_atm_id'), table_name='op')
    op.drop_table('op')
    # ### end Alembic commands ###
