"""empty message

Revision ID: e67c4ab3a703
Revises: 7f0f39e7be4c
Create Date: 2019-07-31 18:20:45.528622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e67c4ab3a703'
down_revision = '7f0f39e7be4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notice', sa.Column('notice_no', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notice', 'notice_no')
    # ### end Alembic commands ###
