"""empty message

Revision ID: ec0d929af0cc
Revises: 9a4653634c61
Create Date: 2019-07-11 22:12:43.479284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec0d929af0cc'
down_revision = '9a4653634c61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('op', 'publish_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('op', sa.Column('publish_date', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
