"""empty message

Revision ID: f1dd3fed376f
Revises: 22e48bc39182
Create Date: 2019-07-29 13:40:19.222169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1dd3fed376f'
down_revision = '22e48bc39182'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('op', sa.Column('document_link', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('op', 'document_link')
    # ### end Alembic commands ###
