"""empty message

Revision ID: f866c235bd1e
Revises: 8426cf645c38
Create Date: 2019-08-13 10:58:27.219748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f866c235bd1e'
down_revision = '8426cf645c38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('supplier_address', sa.Column('correct_at', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('supplier_address', 'correct_at')
    # ### end Alembic commands ###
